---
swagger: '2.0'
info:
  description: This is a typescript microservice template
  version: 1.0.0
  title: Upload CSV
tags:
- name: Meta
  description: health check, etc
- name: Hello
  description: Hello Echo Route
schemes:
- http
paths:
  "/meta/health":
    get:
      tags:
      - Meta
      summary: health-check
      description: ''
      operationId: healthCheck
      produces:
      - application/json
      responses:
        '200':
          description: successful operation
  "/hello/{name}":
    get:
      tags:
      - Hello
      summary: Simple Echo Program
      description: will return hello and the name of the person
      produces:
      - application/json
      parameters:
      - name: name
        in: path
        description: name of person
        required: true
        type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad Request
          schema:
            "$ref": "#/definitions/BadRequest"
        '500':
          description: Server Error
          schema:
            "$ref": "#/definitions/ServerError"
  "/add-items":
    post:
      tags:
      - Addition
      summary: An api to find the sum of all items
      description: will return hello and the name of the person
      produces:
      - application/json
      parameters:
      - in: body
        name: user
        description: list of numbers to add
        example: "[1,2,3]"
        schema:
          type: array
          items:
            type: number
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad Request
          schema:
            "$ref": "#/definitions/BadRequest"
        '500':
          description: Server Error
          schema:
            "$ref": "#/definitions/ServerError"          
definitions:
  BadRequest:
    type: object
    properties:
      message:
        type: string
      body:
        type: object
  ServerError:
    type: object
    properties:
      message:
        type: string
